apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: s3-to-kafka-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: aws-s3-source
    properties:
      useDefaultCredentialsProvider: true
      region: "{{env:AWS_REGION}}"
      bucketNameOrArn: "{{env:BUCKET_NAME}}"
      deleteAfterRead: false
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: kafka-sink
    properties:
      bootstrapServers: "{{env:KAFKA_BOOTSTRAP_SERVERS}}"
      topic: "{{env:KAFKA_TOPIC_NAME}}"
      user: ""
      password: ""
      securityProtocol: "PLAINTEXT"